In [1]:
import xarray as xr

In [2]:
mex = xr.open_dataset("../data/raw/ECMWF_utci_2022_mexico_anual.nc")
mex

<xarray.Dataset> Size: 359MB
Dimensions:  (time: 8760, lat: 77, lon: 133)
Coordinates:
  * time     (time) datetime64[ns] 70kB 2022-01-01 ... 2022-12-31T23:00:00
  * lat      (lat) float64 616B 33.0 32.75 32.5 32.25 ... 14.75 14.5 14.25 14.0
  * lon      (lon) float64 1kB -119.0 -118.8 -118.5 ... -86.5 -86.25 -86.0
Data variables:
    utci     (time, lat, lon) float32 359MB ...
Attributes:
    CDI:                       Climate Data Interface version 1.9.8 (https://...
    Conventions:               CF-1.6
    institution:               European Centre for Medium-Range Weather Forec...
    CDO:                       Climate Data Operators version 1.9.8 (https://...
    cdo_openmp_thread_number:  8
    history:                   Mon Apr  4 07:54:18 2022: ncatted -a _FillValu...
    NCO:                       netCDF Operators version 4.7.8 (Homepage = htt...

In [3]:
utci = mex["utci"] - 273.15
utci

<xarray.DataArray 'utci' (time: 8760, lat: 77, lon: 133)> Size: 359MB
array([[[ -0.8760681 ,   0.6147461 ,   2.3257446 , ...,  17.75885   ,
          17.763275  ,  17.967316  ],
        [ -1.1522522 ,   0.6340637 ,   1.8482666 , ...,  18.02243   ,
          18.02835   ,  18.158752  ],
        [ -1.9740906 ,  -0.46157837,   0.72369385, ...,  18.755371  ,
          18.777466  ,  18.77243   ],
        ...,
        [ 25.05777   ,  25.540466  ,  26.779053  , ...,  20.24591   ,
          22.07074   ,  22.136017  ],
        [ 25.21698   ,  26.032166  ,  27.119324  , ...,  21.174042  ,
          21.078247  ,  20.68686   ],
        [ 25.66925   ,  26.259064  ,  27.134369  , ...,  22.127258  ,
          21.021301  ,  20.686646  ]],

       [[ -4.9784546 ,  -4.085541  ,  -2.5483398 , ...,  16.545837  ,
          16.382263  ,  16.376648  ],
        [ -4.758026  ,  -3.808014  ,  -2.7391663 , ...,  16.948181  ,
          16.714111  ,  16.500763  ],
        [ -4.6171265 ,  -3.8690186 ,  -3.1167297 , ...,  17.9021    ,
          17.720642  ,  17.555115  ],
...
          29.330353  ,  29.019775  ],
        [ 25.301636  ,  25.6044    ,  25.944397  , ...,  27.409607  ,
          27.461884  ,  27.371338  ],
        [ 25.29071   ,  25.725677  ,  26.320343  , ...,  27.433777  ,
          26.48462   ,  26.276001  ]],

       [[  9.136841  ,   8.686462  ,   9.452728  , ...,  15.955719  ,
          15.72879   ,  15.084137  ],
        [  9.613586  ,   8.95282   ,   9.086914  , ...,  17.870758  ,
          17.346497  ,  16.19104   ],
        [ 10.10791   ,  10.003723  ,  10.304993  , ...,  16.604218  ,
          16.682587  ,  16.97406   ],
        ...,
        [ 25.29483   ,  25.381226  ,  25.691833  , ...,  24.510132  ,
          26.467102  ,  27.295288  ],
        [ 25.526764  ,  25.683441  ,  26.065582  , ...,  25.275635  ,
          25.28476   ,  25.408783  ],
        [ 25.668823  ,  26.011261  ,  26.572662  , ...,  25.743439  ,
          25.055511  ,  24.762238  ]]],
      shape=(8760, 77, 133), dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 70kB 2022-01-01 ... 2022-12-31T23:00:00
  * lat      (lat) float64 616B 33.0 32.75 32.5 32.25 ... 14.75 14.5 14.25 14.0
  * lon      (lon) float64 1kB -119.0 -118.8 -118.5 ... -86.5 -86.25 -86.0
Attributes:
    code:         167
    table:        128
    institution:  ECMWF

In [4]:
UTCI_LEVELS = {
    0: (float("-inf"), -40, "Estrés por frío extremo"),
    1: (-40, -27, "Estrés por frío muy fuerte"),
    2: (-27, -13, "Estrés por frío fuerte"),
    3: (-13, 0, "Estrés por frío moderado"),
    4: (0, 9, "Estrés por frío ligero"),
    5: (9, 26, "Sin estrés térmico"),
    6: (26, 32, "Estrés por calor moderado"),
    7: (32, 38, "Estrés por calor fuerte"),
    8: (38, 46, "Estrés por calor muy fuerte"),
    9: (46, float("inf"), "Estrés por calor extremo"),
}


# UTCI_STRESS: tuple[StressCategory, ...] = (
#     StressCategory(0, "Estrés por frío extremo", -np.inf, -40, "#053061"),
#     StressCategory(1, "Estrés por frío muy fuerte", -40, -27, "#2166ac"),
#     StressCategory(2, "Estrés por frío fuerte", -27, -13, "#4393c3"),
#     StressCategory(3, "Estrés por frío moderado", -13, 0, "#92c5de"),
#     StressCategory(4, "Estrés por frío ligero", 0, 9, "#d1e5f0"),
#     StressCategory(5, "Sin estrés térmico", 9, 26, "#d9f0d3"),
#     StressCategory(6, "Estrés por calor moderado", 26, 32, "#fddbc7"),
#     StressCategory(7, "Estrés por calor fuerte", 32, 38, "#f4a582"),
#     StressCategory(8, "Estrés por calor muy fuerte", 38, 46, "#d6604d"),
#     StressCategory(9, "Estrés por calor extremo", 46, np.inf, "#b2182b"),
# )

In [11]:

categorias = xr.full_like(utci, float("nan"))

for categoria, (lim_inf, lim_sup, _) in UTCI_LEVELS.items():

    if lim_inf == float("-inf"):
        mascara = utci <= lim_sup

    elif lim_sup == float("inf"):
        mascara = utci > lim_inf

    else:
        mascara = (utci > lim_inf) & (utci <= lim_sup)

    categorias = xr.where(
        mascara,
        categoria,
        categorias,
    )

categorias = categorias.astype("float32")
valid_count = categorias.notnull().sum("time")


In [12]:
conteos = xr.concat(
    [
        (categorias == categoria).sum("time")
        for categoria in UTCI_LEVELS
    ],
    dim="categoria",
)
conteos

<xarray.DataArray 'utci' (categoria: 10, lat: 77, lon: 133)> Size: 819kB
array([[[   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0],
        ...,
        [   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0]],

       [[   0,    0,    0, ...,   17,   18,   18],
        [   0,    0,    0, ...,   17,   18,   15],
        [   0,    0,    0, ...,   17,   16,   15],
        ...,
        [   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0]],

       [[  21,   13,    2, ...,   95,   95,   98],
        [  16,   10,    3, ...,   83,   75,   65],
        [  13,    7,    1, ...,   76,   73,   70],
        ...,
...
        ...,
        [ 211,  232,  247, ...,  546, 1097, 1134],
        [ 239,  270,  281, ...,  508,  598,  455],
        [ 270,  278,  305, ...,  749,  463,  430]],

       [[   0,    0,    0, ...,  141,  117,   89],
        [   0,    0,    0, ...,  155,  127,  103],
        [   0,    0,    0, ...,  303,  301,  263],
        ...,
        [   0,    0,    0, ...,    0,   20,   18],
        [   0,    0,    0, ...,    0,    1,    0],
        [   0,    0,    0, ...,    6,    0,    0]],

       [[   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0],
        ...,
        [   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0]]], shape=(10, 77, 133))
Coordinates:
  * lat      (lat) float64 616B 33.0 32.75 32.5 32.25 ... 14.75 14.5 14.25 14.0
  * lon      (lon) float64 1kB -119.0 -118.8 -118.5 ... -86.5 -86.25 -86.0
Dimensions without coordinates: categoria

In [13]:
conteos = conteos.assign_coords(
    categoria=list(UTCI_LEVELS.keys())
)


In [14]:
stress_percentage = (
    conteos
    / valid_count
    * 100
)
stress_percentage

<xarray.DataArray 'utci' (categoria: 10, lat: 77, lon: 133)> Size: 819kB
array([[[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        ...,
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00]],

       [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.94063927e-01, 2.05479452e-01, 2.05479452e-01],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.94063927e-01, 2.05479452e-01, 1.71232877e-01],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.94063927e-01, 1.82648402e-01, 1.71232877e-01],
...
         0.00000000e+00, 2.28310502e-01, 2.05479452e-01],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 1.14155251e-02, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         6.84931507e-02, 0.00000000e+00, 0.00000000e+00]],

       [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        ...,
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00]]],
      shape=(10, 77, 133))
Coordinates:
  * categoria  (categoria) int64 80B 0 1 2 3 4 5 6 7 8 9
  * lat        (lat) float64 616B 33.0 32.75 32.5 32.25 ... 14.5 14.25 14.0
  * lon        (lon) float64 1kB -119.0 -118.8 -118.5 ... -86.5 -86.25 -86.0

In [15]:
labels = [
    info[2]
    for info in UTCI_LEVELS.values()
]

stress_percentage = stress_percentage.assign_coords(
    categoria_label=("categoria", labels)
)

In [16]:
stress_percentage

<xarray.DataArray 'utci' (categoria: 10, lat: 77, lon: 133)> Size: 819kB
array([[[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        ...,
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00]],

       [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.94063927e-01, 2.05479452e-01, 2.05479452e-01],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.94063927e-01, 2.05479452e-01, 1.71232877e-01],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.94063927e-01, 1.82648402e-01, 1.71232877e-01],
...
         0.00000000e+00, 2.28310502e-01, 2.05479452e-01],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 1.14155251e-02, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         6.84931507e-02, 0.00000000e+00, 0.00000000e+00]],

       [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        ...,
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00]]],
      shape=(10, 77, 133))
Coordinates:
  * categoria        (categoria) int64 80B 0 1 2 3 4 5 6 7 8 9
    categoria_label  (categoria) <U27 1kB 'Estrés por frío extremo' ... 'Estr...
  * lat              (lat) float64 616B 33.0 32.75 32.5 ... 14.5 14.25 14.0
  * lon              (lon) float64 1kB -119.0 -118.8 -118.5 ... -86.25 -86.0